name: BuildViaZephyrAction

on: 
  push:
  pull_request:
  workflow_dispatch:
  schedule:
  - cron: "0 19 * * 1-5"
jobs:
  installZephyrAndBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: grandcentrix/actions-zephyr-sdk@latest
        with:
          url: https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.15.1/zephyr-sdk-0.15.1_linux-x86_64_minimal.tar.gz
          toolchains: x86_64-zephyr-elf, arm-zephyr-eabi

      - name: InstallWestWorkspace
        run: |
          pip3 install west

          cd ${{github.workspace}}
          cd ..
          west init -m https://github.com/nrfconnect/sdk-nrf --mr v2.1.1 /home/runner/work
          west update
          cd /home/runner/work
          pip3 install -r zephyr/scripts/requirements-base.txt
          sudo apt install --no-install-recommends cmake ninja-build  

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: BuildTargets
        run: |
          west build --pristine -b qemu_x86
          west build --pristine -b thingy91_nrf9160_ns

