name: Build

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:v0.24.5
    strategy:
      matrix:
        sample: [blinky]
        target: [circuitdojo_feather_nrf9160_ns]
    steps:
 #     - name: Checkout
 #       uses: actions/checkout@v2
 #       with:
 #         fetch-depth: 0
 #         path: nfed
#
#      - name: Set variables
#        working-directory: nfed
#        id: vars
#        run: |
#             echo "::set-output name=branch::${GITHUB_REF#refs/*/}"
#             echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

  #      working-directory: nfed
#          west build -b ${{ matrix.target }} -s samples/${{ matrix.sample }} -p
      - name: Build ${{ matrix.sample }} for ${{ matrix.target }}
        run: |
          sudo su
          west init
          cd zephyr
          west build -b qemu_x86 samples/hello_world
          mkdir -p .out
          cp build/zephyr/app_update.bin .out/${{ matrix.sample }}_${{ matrix.target }}_app_update.bin
          cp build/zephyr/merged.hex .out/${{ matrix.sample }}_${{ matrix.target }}_merged.hex

