name: Build

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:v0.24.5
    strategy:
      matrix:
        sample: [blinky]
        target: [circuitdojo_feather_nrf9160_ns]
    steps:
#      - name: Set variables
#        working-directory: nfed
#        id: vars
#        run: |
#             echo "::set-output name=branch::${GITHUB_REF#refs/*/}"
#             echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
#
  #      working-directory: nfed
#          west build -b ${{ matrix.target }} -s samples/${{ matrix.sample }} -p
      - name: Install Connect SDK
        run: |
          west init
          echo "*** PWD"
          pwd
          echo "*** LS"
          ls -l
          west update
          export ZEPHYR_TOOLCHAIN_VARIANT=zephyr
          export ZEPHYR_SDK_INSTALL_DIR=/opt/toolchains/zephyr-sdk-0.15.1/
          cd zephyr

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: nfed

      - name: Build ${{ matrix.sample }} for ${{ matrix.target }}
        run: |
          echo "*** BUILD"
          cd nfed
          echo "*** LS"
          ls -l
          working-directory: nfed
          west build -b qemu_x86 -s Zephyr_BLE_periph_big_data
          echo "*** LS"
          ls -l
          echo "*** RUN"
          west build -t run
#         west build -b qemu_x86 samples/hello_world
#          mkdir -p .out
#          cp build/zephyr/app_update.bin .out/${{ matrix.sample }}_${{ matrix.target }}_app_update.bin
#          cp build/zephyr/merged.hex .out/${{ matrix.sample }}_${{ matrix.target }}_merged.hex

#      - uses: GuillaumeFalourd/assert-command-line-output@v2
#        with:
#          command_line: west build -t run
#          contains: ello
#          expected_result: PASSED

