name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
#    container: zephyrprojectrtos/ci:v0.24.5
    strategy:
      matrix:
        sample: [blinky]
        target: [circuitdojo_feather_nrf9160_ns]
    steps:
      - uses: grandcentrix/actions-zephyr-sdk@latest
        with:
          url: https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.11.4/zephyr-toolchain-arm-0.11.4-setup.run

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
  #        path: nfed

      - name: Set variables
  #      working-directory: nfed
        id: vars
        run: |
             echo "::set-output name=branch::${GITHUB_REF#refs/*/}"
             echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Initialize
  #      working-directory: nfed
        run: |
          pip3 install west
          west init -l .
          west update
          pip3 install -r ../zephyr/scripts/requirements-base.txt

      - name: Build ${{ matrix.sample }} for ${{ matrix.target }}
   #     working-directory: nfed
        run: |
          west build -b ${{ matrix.target }} -s samples/${{ matrix.sample }} -p
          mkdir -p .out
          cp build/zephyr/app_update.bin .out/${{ matrix.sample }}_${{ matrix.target }}_app_update.bin
          cp build/zephyr/merged.hex .out/${{ matrix.sample }}_${{ matrix.target }}_merged.hex

      - name: Archive firmware
        uses: actions/upload-artifact@v2
        with:
          name: nfed_${{ steps.vars.outputs.branch }}_${{ steps.vars.outputs.sha_short }}
          path: .out/
